[tool.poetry]
name = "ninechronicles-iap"
version = "0.1.0"
description = "NineChronicles In-app Purchase Service"
authors = ["hyeon <hyeon+iap@planetariumhq.com>"]
readme = "README.md"
packages = [{include = "iap"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.1"
psycopg2-binary = "^2.9.6"
sqlalchemy = "^2.0.12"
uvicorn = "^0.22.0"
boto3 = "^1.26.137"


[tool.poetry.group.dev.dependencies]
ipython = "^8.13.1"
pytest = "^7.3.1"
alembic = "^1.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
