"""Add unique constraint

Revision ID: 2822c456abc3
Revises: 5bf8ab4f3b13
Create Date: 2023-12-05 01:11:38.405536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2822c456abc3'
down_revision = '5bf8ab4f3b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("voucher_request_receipt_id_unique", 'voucher_request', ['receipt_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("voucher_request_receipt_id_unique", 'voucher_request', type_='unique')
    # ### end Alembic commands ###
