"""Add apple SKU for K

Revision ID: 3378efa82b6c
Revises: f6de778b7fe3
Create Date: 2024-05-10 14:35:14.164913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3378efa82b6c'
down_revision = 'f6de778b7fe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('apple_sku_k', sa.Text(), nullable=True))
    op.execute("UPDATE product SET apple_sku_k=concat(apple_sku, '_k')")
    op.alter_column("product", "apple_sku_k", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'apple_sku_k')
    # ### end Alembic commands ###
