"""Create garage models

Revision ID: 3e29896ac79d
Revises: ebf65a2e4fb4
Create Date: 2023-06-12 12:33:03.777601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e29896ac79d'
down_revision = 'ebf65a2e4fb4'
branch_labels = None
depends_on = None

tx_status = sa.Enum('CREATED', 'STAGED', 'SUCCESS', 'FAILURE', 'INVALID', 'NOT_FOUND', 'UNKNOWN', name='txstatus')
garage_action_type = sa.Enum('LOAD', 'TRANSFER', 'UNLOAD', name='garageactiontype')
ticker = sa.Enum('NCG', 'CRYSTAL', 'GARAGE', name='currency')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garage_action_history',
    sa.Column('block_index', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.Text(), nullable=False),
    sa.Column('tx_hash', sa.Text(), nullable=False),
    sa.Column('tx_status', sa.Enum('CREATED', 'STAGED', 'SUCCESS', 'FAILURE', 'INVALID', 'NOT_FOUND', 'UNKNOWN', name='txstatus'), nullable=True),
    sa.Column('action_type', sa.Enum('LOAD', 'TRANSFER', 'UNLOAD', name='garageactiontype'), nullable=False),
    sa.Column('signer', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_action_history_action_type'), 'garage_action_history', ['action_type'], unique=False)
    op.create_index(op.f('ix_garage_action_history_signer'), 'garage_action_history', ['signer'], unique=False)
    op.create_table('garage_fav_status',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Enum('NCG', 'CRYSTAL', 'GARAGE', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_fav_status_ticker'), 'garage_fav_status', ['ticker'], unique=False)
    op.create_table('garage_item_status',
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('fungible_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_item_status_fungible_id'), 'garage_item_status', ['fungible_id'], unique=False)
    op.create_table('garage_fav_history',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('ticker', sa.Enum('NCG', 'CRYSTAL', 'GARAGE', name='currency'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['garage_action_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_fav_history_ticker'), 'garage_fav_history', ['ticker'], unique=False)
    op.create_table('garage_item_history',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('fungible_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['garage_action_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garage_item_history_fungible_id'), 'garage_item_history', ['fungible_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garage_item_history_fungible_id'), table_name='garage_item_history')
    op.drop_table('garage_item_history')
    op.drop_index(op.f('ix_garage_fav_history_ticker'), table_name='garage_fav_history')
    op.drop_table('garage_fav_history')
    op.drop_index(op.f('ix_garage_item_status_fungible_id'), table_name='garage_item_status')
    op.drop_table('garage_item_status')
    op.drop_index(op.f('ix_garage_fav_status_ticker'), table_name='garage_fav_status')
    op.drop_table('garage_fav_status')
    op.drop_index(op.f('ix_garage_action_history_signer'), table_name='garage_action_history')
    op.drop_index(op.f('ix_garage_action_history_action_type'), table_name='garage_action_history')
    op.drop_table('garage_action_history')
    tx_status.drop(op.get_bind(), checkfirst=False)
    garage_action_type.drop(op.get_bind(), checkfirst=False)
    ticker.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
