"""Set non-nullable columns

Revision ID: 4beb3c9fcd4b
Revises: d09361e553f0
Create Date: 2023-10-25 22:51:04.194337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4beb3c9fcd4b'
down_revision = 'd09361e553f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'size',
               existing_type=postgresql.ENUM('ONE_BY_ONE', 'ONE_BY_TWO', 'ONE_BY_THREE', 'ONE_BY_FOUR', 'TWO_BY_ONE', 'TWO_BY_TWO', 'TWO_BY_THREE', 'TWO_BY_FOUR', 'THREE_BY_ONE', 'THREE_BY_TWO', 'THREE_BY_THREE', 'THREE_BY_FOUR', 'FOUR_BY_ONE', 'FOUR_BY_TWO', 'FOUR_BY_THREE', 'FOUR_BY_FOUR', name='productassetuisize'),
               nullable=False)
    op.alter_column('product', 'path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'l10n_key',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'l10n_key',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'size',
               existing_type=postgresql.ENUM('ONE_BY_ONE', 'ONE_BY_TWO', 'ONE_BY_THREE', 'ONE_BY_FOUR', 'TWO_BY_ONE', 'TWO_BY_TWO', 'TWO_BY_THREE', 'TWO_BY_FOUR', 'THREE_BY_ONE', 'THREE_BY_TWO', 'THREE_BY_THREE', 'THREE_BY_FOUR', 'FOUR_BY_ONE', 'FOUR_BY_TWO', 'FOUR_BY_THREE', 'FOUR_BY_FOUR', name='productassetuisize'),
               nullable=True)
    # ### end Alembic commands ###
