"""Add WEB and WEB_TEST to store enum

Revision ID: 5618fef65b02
Revises: f7b21b5e99be
Create Date: 2025-10-27 21:29:34.841625

"""
import sqlalchemy as sa
from sqlalchemy import Text

from alembic import op

# revision identifiers, used by Alembic.
revision = '5618fef65b02'
down_revision = 'f7b21b5e99be'
branch_labels = None
depends_on = None

old_enum = (
    "TEST", "APPLE", "GOOGLE", "APPLE_TEST", "GOOGLE_TEST"
)
new_enum = sorted(old_enum + ("WEB", "WEB_TEST"))

old_store = sa.Enum(*old_enum, name="store")
new_store = sa.Enum(*new_enum, name="store")
tmp_store = sa.Enum(*new_enum, name="_store")

receipt_table = sa.sql.table(
    "receipt",
    sa.Column("store", new_store, nullable=False),
    sa.Column("order_id", Text, nullable=False)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_store.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")
    # Drop old enum with CASCADE to handle dependent objects
    op.execute("DROP TYPE store CASCADE")
    new_store.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert WEB and WEB_TEST receipts to GOOGLE_TEST for safety
    op.execute(receipt_table.update()
               .where(receipt_table.c.store.in_(['WEB', 'WEB_TEST']))
               .values(store="GOOGLE_TEST")
               )
    tmp_store.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")
    # Drop new enum with CASCADE to handle dependent objects
    op.execute("DROP TYPE store CASCADE")
    old_store.create(op.get_bind(), checkfirst=False)
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
