"""Add WEB and WEB_TEST to store enum

Revision ID: 5618fef65b02
Revises: f7b21b5e99be
Create Date: 2025-10-27 21:29:34.841625

"""
import sqlalchemy as sa
from sqlalchemy import Text

from alembic import op

# revision identifiers, used by Alembic.
revision = '5618fef65b02'
down_revision = 'f7b21b5e99be'
branch_labels = None
depends_on = None

old_enum = (
    "TEST", "APPLE", "GOOGLE", "APPLE_TEST", "GOOGLE_TEST"
)
new_enum = sorted(old_enum + ("WEB", "WEB_TEST"))

old_store = sa.Enum(*old_enum, name="store")
new_store = sa.Enum(*new_enum, name="store")
tmp_store = sa.Enum(*new_enum, name="_store")

receipt_table = sa.sql.table(
    "receipt",
    sa.Column("store", new_store, nullable=False),
    sa.Column("order_id", Text, nullable=False)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_store.create(op.get_bind(), checkfirst=False)

    # Update receipt table
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")

    # Check if price table has store column before updating
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    price_columns = [col['name'] for col in inspector.get_columns('price')]

    if 'store' in price_columns:
        # Update price table if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE _store USING store::text::_store")

    # Drop old enum (now safe since all columns are converted)
    op.execute("DROP TYPE store")

    # Create new enum
    new_store.create(op.get_bind(), checkfirst=False)

    # Convert back to new enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")

    if 'store' in price_columns:
        # Convert price table back to new enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE store USING store::text::store")

    # Clean up temporary enum
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert WEB and WEB_TEST receipts to GOOGLE_TEST for safety
    op.execute(receipt_table.update()
               .where(receipt_table.c.store.in_(['WEB', 'WEB_TEST']))
               .values(store="GOOGLE_TEST")
               )

    # Check if price table has store column before updating
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    price_columns = [col['name'] for col in inspector.get_columns('price')]

    if 'store' in price_columns:
        # Convert WEB and WEB_TEST prices to GOOGLE_TEST for safety
        op.execute("UPDATE price SET store = 'GOOGLE_TEST' WHERE store IN ('WEB', 'WEB_TEST')")

    tmp_store.create(op.get_bind(), checkfirst=False)

    # Convert both tables to temporary enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")

    if 'store' in price_columns:
        # Convert price table to temporary enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE _store USING store::text::_store")

    # Drop new enum (now safe since all columns are converted)
    op.execute("DROP TYPE store")

    # Create old enum
    old_store.create(op.get_bind(), checkfirst=False)

    # Convert back to old enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")

    if 'store' in price_columns:
        # Convert price table back to old enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE store USING store::text::store")

    # Clean up temporary enum
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
