"""Update DB schema to manage tx data

Revision ID: 57e65ed34bd6
Revises: 32e8805e8364
Create Date: 2023-11-23 16:37:41.334378

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '57e65ed34bd6'
down_revision = '32e8805e8364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('tx', sa.Text(), nullable=True))
    op.add_column('receipt', sa.Column('nonce', sa.Integer(), nullable=True))
    op.add_column('receipt', sa.Column('bridged_tx_id', sa.Text(), nullable=True))
    op.add_column('receipt', sa.Column('bridged_tx_status',
                                       postgresql.ENUM('CREATED', 'STAGED', 'SUCCESS', 'FAILURE', 'INVALID',
                                                       'NOT_FOUND', 'FAIL_TO_CREATE', 'UNKNOWN', name='txstatus'),
                                       nullable=True))
    op.create_index(op.f('ix_receipt_bridged_tx_id'), 'receipt', ['bridged_tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_bridged_tx_id'), table_name='receipt')
    op.drop_column('receipt', 'bridged_tx_status')
    op.drop_column('receipt', 'bridged_tx_id')
    op.drop_column('receipt', 'nonce')
    op.drop_column('receipt', 'tx')
    # ### end Alembic commands ###
