"""Update receipt model

Revision ID: 64dd54c4aef4
Revises: 4673eee05e67
Create Date: 2023-07-03 12:20:44.688579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dd54c4aef4'
down_revision = '4673eee05e67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("receipt", "inventory_addr", new_column_name="avatar_addr")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("receipt", "avatar_addr", new_column_name="inventory_addr")
    # ### end Alembic commands ###
