"""Add is_free column

Revision ID: a2df38682595
Revises: 2822c456abc3
Create Date: 2024-01-18 13:55:23.731546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2df38682595'
down_revision = '2822c456abc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_free', sa.Boolean(), nullable=True, default=False))
    op.execute("UPDATE product SET is_free=FALSE")
    op.alter_column("product", "is_free", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_free')
    # ### end Alembic commands ###
