"""Add REDEEM to store enum

Revision ID: b1d5e1dc71ea
Revises: 5618fef65b02
Create Date: 2025-12-15 17:38:28

"""
import sqlalchemy as sa
from sqlalchemy import Text

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b1d5e1dc71ea'
down_revision = '5618fef65b02'
branch_labels = None
depends_on = None

old_enum = (
    "TEST", "APPLE", "GOOGLE", "WEB", "APPLE_TEST", "GOOGLE_TEST", "WEB_TEST"
)
new_enum = sorted(old_enum + ("REDEEM",))

old_store = sa.Enum(*old_enum, name="store")
new_store = sa.Enum(*new_enum, name="store")
tmp_store = sa.Enum(*new_enum, name="_store")

receipt_table = sa.sql.table(
    "receipt",
    sa.Column("store", new_store, nullable=False),
    sa.Column("order_id", Text, nullable=False)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_store.create(op.get_bind(), checkfirst=False)

    # Update receipt table
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")

    # Check if price table has store column before updating
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    price_columns = [col['name'] for col in inspector.get_columns('price')]

    if 'store' in price_columns:
        # Drop default before altering type (if exists)
        result = connection.execute(sa.text("""
            SELECT column_default
            FROM information_schema.columns
            WHERE table_name = 'price' AND column_name = 'store'
        """))
        default_row = result.fetchone()
        default_value = default_row[0] if default_row else None

        # Drop default if exists
        if default_value:
            op.execute("ALTER TABLE price ALTER COLUMN store DROP DEFAULT")

        # Update price table if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE _store USING store::text::_store")

        # Restore default if it existed (extract enum value from default string)
        if default_value:
            # Default format is usually like: 'GOOGLE'::store or 'GOOGLE'
            default_str = str(default_value).split("::")[0].strip("'\"")
            if default_str in new_enum:  # Only restore if it's in new enum
                op.execute(f"ALTER TABLE price ALTER COLUMN store SET DEFAULT '{default_str}'::_store")

    # Drop old enum (now safe since all columns are converted)
    op.execute("DROP TYPE store")

    # Create new enum
    new_store.create(op.get_bind(), checkfirst=False)

    # Convert back to new enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")

    if 'store' in price_columns:
        # Drop default before altering type (if exists)
        result = connection.execute(sa.text("""
            SELECT column_default
            FROM information_schema.columns
            WHERE table_name = 'price' AND column_name = 'store'
        """))
        default_row = result.fetchone()
        default_value = default_row[0] if default_row else None

        # Drop default if exists
        if default_value:
            op.execute("ALTER TABLE price ALTER COLUMN store DROP DEFAULT")

        # Convert price table back to new enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE store USING store::text::store")

        # Restore default if it existed (extract enum value from default string)
        if default_value:
            # Default format is usually like: 'GOOGLE'::store or 'GOOGLE'
            default_str = str(default_value).split("::")[0].strip("'\"")
            if default_str in new_enum:  # Only restore if it's in new enum
                op.execute(f"ALTER TABLE price ALTER COLUMN store SET DEFAULT '{default_str}'::store")

    # Clean up temporary enum
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert REDEEM receipts to GOOGLE_TEST for safety
    op.execute(receipt_table.update()
               .where(receipt_table.c.store == 'REDEEM')
               .values(store="GOOGLE_TEST")
               )

    # Check if price table has store column before updating
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    price_columns = [col['name'] for col in inspector.get_columns('price')]

    if 'store' in price_columns:
        # Convert REDEEM prices to GOOGLE_TEST for safety
        op.execute("UPDATE price SET store = 'GOOGLE_TEST' WHERE store = 'REDEEM'")

    tmp_store.create(op.get_bind(), checkfirst=False)

    # Convert both tables to temporary enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE _store USING store::text::_store")

    if 'store' in price_columns:
        # Drop default before altering type (if exists)
        # Query to check if default exists and get its value
        result = connection.execute(sa.text("""
            SELECT column_default
            FROM information_schema.columns
            WHERE table_name = 'price' AND column_name = 'store'
        """))
        default_row = result.fetchone()
        default_value = default_row[0] if default_row else None

        # Drop default if exists
        if default_value:
            op.execute("ALTER TABLE price ALTER COLUMN store DROP DEFAULT")

        # Convert price table to temporary enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE _store USING store::text::_store")

        # Restore default if it existed (extract enum value from default string)
        if default_value:
            # Default format is usually like: 'GOOGLE'::store or 'GOOGLE'
            default_str = str(default_value).split("::")[0].strip("'\"")
            if default_str in old_enum:  # Only restore if it's in old enum
                op.execute(f"ALTER TABLE price ALTER COLUMN store SET DEFAULT '{default_str}'::_store")

    # Drop new enum (now safe since all columns are converted)
    op.execute("DROP TYPE store")

    # Create old enum
    old_store.create(op.get_bind(), checkfirst=False)

    # Convert back to old enum
    op.execute("ALTER TABLE receipt ALTER COLUMN store TYPE store USING store::text::store")

    if 'store' in price_columns:
        # Drop default before altering type (if exists)
        result = connection.execute(sa.text("""
            SELECT column_default
            FROM information_schema.columns
            WHERE table_name = 'price' AND column_name = 'store'
        """))
        default_row = result.fetchone()
        default_value = default_row[0] if default_row else None

        # Drop default if exists
        if default_value:
            op.execute("ALTER TABLE price ALTER COLUMN store DROP DEFAULT")

        # Convert price table back to old enum if store column exists
        op.execute("ALTER TABLE price ALTER COLUMN store TYPE store USING store::text::store")

        # Restore default if it existed (extract enum value from default string)
        if default_value:
            # Default format is usually like: 'GOOGLE'::store or 'GOOGLE'
            default_str = str(default_value).split("::")[0].strip("'\"")
            if default_str in old_enum:  # Only restore if it's in old enum
                op.execute(f"ALTER TABLE price ALTER COLUMN store SET DEFAULT '{default_str}'::store")

    # Clean up temporary enum
    tmp_store.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
