"""Delete planet_id to merge mileage

Revision ID: bbbcfcbe1487
Revises: 5e7148bfcf36
Create Date: 2024-12-05 09:45:18.213511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbbcfcbe1487'
down_revision = '5e7148bfcf36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_planet_agent', 'mileage', type_='unique')
    op.drop_index('ix_mileage_agent_planet', table_name='mileage')
    op.create_index('ix_mileage_agent_planet', 'mileage', ['agent_addr'], unique=False)
    op.create_unique_constraint('unique_agent', 'mileage', ['agent_addr'])
    op.drop_column('mileage', 'planet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mileage', sa.Column('planet_id', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_agent', 'mileage', type_='unique')
    op.drop_index('ix_mileage_agent_planet', table_name='mileage')
    op.create_index('ix_mileage_agent_planet', 'mileage', ['planet_id', 'agent_addr'], unique=False)
    op.create_unique_constraint('unique_planet_agent', 'mileage', ['planet_id', 'agent_addr'])
    # ### end Alembic commands ###
