"""Update product model: Add paths

Revision ID: d09361e553f0
Revises: 74f4b954bd1b
Create Date: 2023-09-20 11:11:55.829407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09361e553f0'
down_revision = '74f4b954bd1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('bg_path', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('popup_path_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'popup_path_key')
    op.drop_column('product', 'bg_path')
    # ### end Alembic commands ###
