"""Add message column to receipt

Revision ID: e75f93e4cc06
Revises: b7a685e5ef1c
Create Date: 2023-11-06 10:40:51.109008

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e75f93e4cc06'
down_revision = 'b7a685e5ef1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('msg', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'msg')
    # ### end Alembic commands ###
