"""Add AvatarLevel table

Revision ID: f6de778b7fe3
Revises: 90ff6ac09fe5
Create Date: 2024-03-20 11:39:30.281858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6de778b7fe3'
down_revision = '90ff6ac09fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_level',
    sa.Column('agent_addr', sa.Text(), nullable=False),
    sa.Column('avatar_addr', sa.Text(), nullable=False),
    sa.Column('planet_id', sa.LargeBinary(length=12), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_avatar_planet', 'avatar_level', ['avatar_addr', 'planet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_avatar_planet', table_name='avatar_level')
    op.drop_table('avatar_level')
    # ### end Alembic commands ###
