"""Update Receipt Model

Revision ID: 2e9204a46dc7
Revises: 88d48811f7a9
Create Date: 2023-06-19 15:12:51.590338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9204a46dc7'
down_revision = '88d48811f7a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('receipt', sa.Column('inventoryAddress', sa.Text(), nullable=True))
    op.drop_index('ix_receipt_address', table_name='receipt')
    op.create_index(op.f('ix_receipt_uuid'), 'receipt', ['uuid'], unique=False)
    op.drop_column('receipt', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_receipt_uuid'), table_name='receipt')
    op.create_index('ix_receipt_address', 'receipt', ['address'], unique=False)
    op.drop_column('receipt', 'inventoryAddress')
    op.drop_column('receipt', 'uuid')
    # ### end Alembic commands ###
