"""Add planet_id to sign history

Revision ID: 3c5ca13ddcf5
Revises: bdb01e673e04
Create Date: 2023-11-22 04:18:17.073994

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3c5ca13ddcf5'
down_revision = 'bdb01e673e04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign_history', sa.Column('planet_id', sa.LargeBinary(length=12), nullable=True))
    op.execute("UPDATE sign_history SET planet_id = '0x000000000000'::bytea")
    op.alter_column("sign_history", "planet_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign_history', 'planet_id')
    # ### end Alembic commands ###
