"""Mileage history table

Revision ID: 5e7148bfcf36
Revises: b3b8a0d4eba5
Create Date: 2024-12-05 09:43:59.814617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e7148bfcf36'
down_revision = 'b3b8a0d4eba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_addr', sa.Text(), nullable=False),
    sa.Column('planet_id', sa.LargeBinary(length=12), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mileage_history')
    # ### end Alembic commands ###
