"""planet_id of Mileage is nullable

Revision ID: 6cdd269f8204
Revises: b3b8a0d4eba5
Create Date: 2024-12-04 11:51:33.545231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cdd269f8204'
down_revision = 'b3b8a0d4eba5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mileage', 'planet_id',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mileage', 'planet_id',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
