"""Update product model: Add L10N

Revision ID: 74f4b954bd1b
Revises: 3c96c08258a1
Create Date: 2023-09-19 11:30:08.846337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f4b954bd1b'
down_revision = '3c96c08258a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('l10n_key', sa.Text(), nullable=True))
    op.add_column('product', sa.Column('l10n_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'l10n_key')
    op.drop_column('category', 'l10n_key')
    # ### end Alembic commands ###
