"""Create Receipt model

Revision ID: 88d48811f7a9
Revises: 1ab63d3081f4
Create Date: 2023-06-14 16:56:48.269878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88d48811f7a9'
down_revision = '1ab63d3081f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('store', postgresql.ENUM('TEST', 'APPLE', 'GOOGLE', 'APPLE_TEST', 'GOOGLE_TEST', name='store'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('INIT', 'VALIDATION_REQUEST', 'VALID', 'INVALID', 'UNKNOWN', name='receiptstatus'), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('tx_id', sa.Text(), nullable=True),
    sa.Column('tx_status', postgresql.ENUM('CREATED', 'STAGED', 'SUCCESS', 'FAILURE', 'INVALID', 'NOT_FOUND', 'UNKNOWN', name='txstatus', create_type=False), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_address'), 'receipt', ['address'], unique=False)
    op.create_index(op.f('ix_receipt_store'), 'receipt', ['store'], unique=False)
    op.create_index(op.f('ix_receipt_tx_id'), 'receipt', ['tx_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_tx_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_store'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_address'), table_name='receipt')
    op.drop_table('receipt')
    # ### end Alembic commands ###
