"""Add uuid column to SignHistory

Revision ID: 8c0698de32b6
Revises: da51c592e62c
Create Date: 2023-09-27 11:20:11.121958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0698de32b6'
down_revision = 'da51c592e62c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sign_history', sa.Column('uuid', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_sign_history_uuid'), 'sign_history', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_history_uuid'), table_name='sign_history')
    op.drop_column('sign_history', 'uuid')
    # ### end Alembic commands ###
