"""Update Receipt model

Revision ID: 91a49d2a3db2
Revises: b600e296a7df
Create Date: 2023-06-23 16:29:48.520175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a49d2a3db2'
down_revision = 'b600e296a7df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('order_id', sa.Text(), nullable=False))
    op.add_column('receipt', sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('receipt', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('receipt', sa.Column('agent_addr', sa.Text(), nullable=True))
    op.alter_column('receipt', "inventoryAddress", new_column_name="inventory_addr")
    op.create_foreign_key("receipt_product_id_fkey", 'receipt', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("receipt", "inventory_addr", new_column_name="inventoryAddress")
    op.drop_constraint("receipt_product_id_fkey", 'receipt', type_='foreignkey')
    op.drop_column('receipt', 'agent_addr')
    op.drop_column('receipt', 'product_id')
    op.drop_column('receipt', 'purchased_at')
    op.drop_column('receipt', 'order_id')
    # ### end Alembic commands ###
