"""Update Product model

Revision ID: b4f422fd0e05
Revises: 91a49d2a3db2
Create Date: 2023-06-26 15:47:17.448645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f422fd0e05'
down_revision = '91a49d2a3db2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fungible_item_product', "item_id", new_column_name="sheet_item_id")
    op.alter_column('fungible_item_product', "fungible_id", new_column_name="fungible_item_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fungible_item_product', "sheet_item_id", new_column_name="item_id")
    op.alter_column('fungible_item_product', "fungible_item_id", new_column_name="fungible_id")
    # ### end Alembic commands ###
