"""Add active to Price model

Revision ID: b5e0d5e83ff7
Revises: b4f422fd0e05
Create Date: 2023-06-29 15:36:31.196282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e0d5e83ff7'
down_revision = 'b4f422fd0e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE price SET active=FALSE")
    op.alter_column("price", "active", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'active')
    # ### end Alembic commands ###
