"""Create product model

Revision ID: b600e296a7df
Revises: 2e9204a46dc7
Create Date: 2023-06-22 17:38:56.198010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b600e296a7df'
down_revision = '2e9204a46dc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('google_sku', sa.Text(), nullable=True),
    sa.Column('apple_sku', sa.Text(), nullable=True),
    sa.Column('product_type', postgresql.ENUM('SINGLE', 'PKG', name='producttype'), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('weekly_limit', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fungible_asset_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ticker', postgresql.ENUM('NCG', 'CRYSTAL', 'GARAGE', name='currency', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fungible_item_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fungible_id', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store', postgresql.ENUM('TEST', 'APPLE', 'GOOGLE', 'APPLE_TEST', 'GOOGLE_TEST', name='store', create_type=False), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('fungible_item_product')
    op.drop_table('fungible_asset_product')
    op.drop_table('product')
    # ### end Alembic commands ###
