"""Create SignHistory model

Revision ID: da51c592e62c
Revises: d09361e553f0
Create Date: 2023-09-26 17:19:42.961533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da51c592e62c'
down_revision = 'd09361e553f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_history',
    sa.Column('request_type', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('plain_value', sa.Text(), nullable=True),
    sa.Column('tx_id', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sign_history_request_type'), 'sign_history', ['request_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_history_request_type'), table_name='sign_history')
    op.drop_table('sign_history')
    # ### end Alembic commands ###
