name: Build Docker Images

on:
  push:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker:
          - repo: planetariumhq/iap-api
            dockerfile: Dockerfile.Api
          - repo: planetariumhq/iap-worker
            dockerfile: Dockerfile.Worker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v8,linux/amd64
      -
        name: Login to Docker Hub
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ matrix.docker.repo }}:git-${{ github.sha }}
          file: ${{ matrix.docker.dockerfile }}
        env:
          BUILDKIT_PROGRESS: "plain"
