on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  frontend:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: iap/frontend/node_modules
          key: poetry-${{ runner.os }}-${{ hashFiles('iap/frontend/yarn.lock') }}

      - name: Install dependencies
        env:
          STAGE: ${{ vars.STAGE }}
        run: |
          pushd iap/frontend
          yarn install
          sed -i "s/export const STAGE=\"local\";/export const STAGE=\"$STAGE\";/" src/const.js
          yarn build
          popd

      - name: Export artifact
        id: frontend-artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: |
            iap/frontend/build
          retention-days: 2

  slack_notification:
    uses: ./.github/workflows/slack_message.yml
    needs: frontend
    if: ${{ failure() }}
    with:
      environment: ${{ inputs.environment }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
