name: Deploy NineChronicles.IAP

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-in-project: true

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: iap/frontend/node_modules
          key: poetry-${{ runner.os }}-${{ hashFiles('iap/frontend/yarn.lock') }}

      - name: Install dependencies
        run: |
          poetry install
          pushd iap/frontend
          yarn install
          popd
          yarn add aws-cdk

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: iap/frontend/build

      - name: Download iap_layer artifact
        uses: actions/download-artifact@v3
        with:
          name: iap_layer
          path: iap/layer

      - name: Download worker_layer artifact
        uses: actions/download-artifact@v3
        with:
          name: worker_layer
          path: worker/layer

      - name: Synth stack
        env:
          STAGE: ${{ vars.STAGE }}
          REGION_NAME: ${{ vars.REGION_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEADLESS: ${{ vars.HEADLESS }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
          GOOGLE_CREDENTIAL: ${{ secrets.GOOGLE_CREDENTIAL }}
          GOOGLE_PACKAGE_NAME: ${{ vars.GOOGLE_PACKAGE_NAME }}
        run: |
          source $VENV
          yarn cdk synth

      - name: Deploy stack
        id: deployment
        env:
          STAGE: ${{ vars.STAGE }}
          REGION_NAME: ${{ vars.REGION_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HEADLESS: ${{ vars.HEADLESS }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
          GOOGLE_CREDENTIAL: ${{ secrets.GOOGLE_CREDENTIAL }}
          GOOGLE_PACKAGE_NAME: ${{ vars.GOOGLE_PACKAGE_NAME }}
        run: |
          echo "TIME=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_OUTPUT
          source $VENV
          yarn cdk deploy --all --require-approval never -O output.txt
          cat output.txt
          ARRAY=(`grep -e "https://.*/$STAGE/" output.txt | tr "\"", "\n"`)
          echo "SERVICE_HOST=${ARRAY[-1]}" >> $GITHUB_OUTPUT

      - name: Slack noti
        uses: ./.github/workflows/slack_message.yml
        with:
          environment: ${{ inputs.environment }}

#      - name: Upgrade DB Schema
#        env:
#          STAGE: ${{vars.STAGE}}
#          REGION_NAME: ${{ vars.REGION_NAME }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          source $VENV
#          pushd common
#          python scripts/update_alembic_ini.py
#          alembic upgrade head -n ${{vars.STAGE}}
#          popd
